#!/bin/sh -eu

# Automatic backup script
#
# Link from:
# /etc/cron.weekly/

SCRIPT_DIR=$(dirname "$(realpath "$0")")
ROOT=${SCRIPT_DIR}/../backup
LOG_FILE="/root/bkup.log"

"${ROOT}/bkup_all.sh" >> "${LOG_FILE}" 2>&1
