#!/bin/sh

# Automatic backup script
#
# Copy to:
# /etc/cron.weekly/
# Clone this repository to:
# /root/DollsKit

ROOT=/root/DollsKit/root/backup
LOG=/root/bkup.log

echo -------------------------------------------------------------------------------- >> ${LOG}
date -R >> ${LOG}
echo -------------------------------------------------------------------------------- >> ${LOG}

python3 ${ROOT}/bkup.py \
--mount-check /media/usbbkup \
--reserved-size 30 \
--exclude-from ${ROOT}/bkup_exclude.txt \
/ /media/usbbkup/full \
>> ${LOG} 2>&1
