#!/bin/sh

# Automatic backup script
#
# Copy to:
# /etc/cron.daily/
# Clone this repository to:
# /root/DollsKit

ROOT=/root/DollsKit/root/backup
LOG=/root/wpbkup.log

echo -------------------------------------------------------------------------------- >> ${LOG}
date -R >> ${LOG}
echo -------------------------------------------------------------------------------- >> ${LOG}

python3 ${ROOT}/bkup.py \
--mount-check /media/usbbkup \
--keep-count 30 \
/var/www/html/ /media/usbbkup/wp \
>> ${LOG} 2>&1
