#!/bin/sh

# Automatic backup script
#
# Link from:
# /etc/cron.weekly/

SCRIPT_DIR=$(dirname $(realpath $0))
ROOT=${SCRIPT_DIR}/../backup
BKUP_ROOT=/mnt/localbkup
LOG=/root/bkup.log

echo -------------------------------------------------------------------------------- >> ${LOG}
date -R >> ${LOG}
echo -------------------------------------------------------------------------------- >> ${LOG}

python3 ${ROOT}/bkup.py \
--tag full \
--mount-check ${BKUP_ROOT} \
--reserved-size 30 \
--exclude-from ${ROOT}/bkup_exclude.txt \
/ ${BKUP_ROOT}/full \
>> ${LOG} 2>&1
