#!/bin/bash -eu

# Automatic backup script
#
# Link from:
# /etc/cron.weekly/

# ------------------------------------------------------------------------------
# Config (can be overriden by ENVVAR)
LOG_FILE=${LOG_FILE:-"/root/growi_bkup.log"}
PROJS=${PROJS:-"growi-public growi-private"}
VOLUMES=${VOLUMES:-"es_data growi_data mongo_configdb mongo_db page_bulk_export_tmp"}
# ------------------------------------------------------------------------------

PROJS_ARRAY=( "${PROJS}" )

SELF_DIR=$(dirname "$(realpath "$0")")
ROOT=${SELF_DIR}/../backup

for PROJ in "${PROJS_ARRAY[@]}"; do
    "${ROOT}/bkup_docker.sh" "${PROJ}" "${VOLUMES}" >> "${LOG_FILE}" 2>&1
done
