#!/bin/sh -eu

# Create a file: /root/mydns
# user:pass
# permission recommended: 400

# Link from:
# /etc/cron.daily/

CRED=$(cat /root/mydns)
MYDNS=https://www.mydns.jp/login.html
curl -u "$CRED" "$MYDNS"
