#!/bin/sh -eu

# Create a file: /root/mydns
# user1:pass1
# user2:pass2
# ...
# permission recommended: 400

# Link from:
# /etc/cron.daily/

LISTFILE=/root/mydns
MYDNS=https://www.mydns.jp/login.html

xargs --verbose --arg-file "$LISTFILE" -I{} curl -u {} "$MYDNS"
