language: cpp
sudo: false

os: linux
dist: bionic
compiler:
  - clang
  - gcc
env:
  global:
    - MAKEFLAGS="-j2"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

addons:
  apt:
    packages:
    - libmicrohttpd-dev
    - graphviz

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make
  - make fulltest
  - make doc
