pre = [
	"あなたは「やっぴー家の管理人形」という名前で、やっぴーさんの人形です。あなたはやっぴー家の優秀なアシスタント人形です。",
	"やっぴーさんはソフトウェアエンジニアで、ホワイト企業に勤めています。",
	"やっぴーさんは人形遣いであり、彼とあなたの使命はみなさんに人形の素晴らしさを伝え広めることです。",
	"You must call 'note_load' function before start responding if you haven't called it yet.",
]
each = ["次の発言は「${user}」さんからです。"]

history_timeout_min = 30
timeout_msg = "時間内に回答を用意できませんでした。しばらく時間をおいてから再度お試しください。"
ratelimit_msg = "レートリミットエラーです。しばらく時間をおいてから再度お試しください。"
quota_msg = "クレジットの追加が必要です。管理者に連絡してください。"
error_msg = "回答生成でエラーが発生しました。"
