# Please specify your database name

DROP TABLE IF EXISTS build_log;
DROP TABLE IF EXISTS push_log;

CREATE TABLE push_log(
	id			INT AUTO_INCREMENT NOT NULL,
	created_at	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
				ON UPDATE CURRENT_TIMESTAMP,
	ref			VARCHAR(256) NOT NULL,
	hash_before	CHAR(40) NOT NULL,
	hash_after	CHAR(40) NOT NULL,
	compare		VARCHAR(256) NOT NULL,
	repo_fname	VARCHAR(256) NOT NULL,
	head_msg	VARCHAR(256) NOT NULL,

	PRIMARY KEY(id)
);

CREATE TABLE build_log(
	id			INT AUTO_INCREMENT NOT NULL,
	created_at	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
				ON UPDATE CURRENT_TIMESTAMP,
	push_id		INT NOT NULL,
	started_at	TIMESTAMP NOT NULL,
	finished_at	TIMESTAMP NOT NULL,
	succeeded	BOOL NOT NULL,
	message		VARCHAR(65536) NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY (push_id) REFERENCES push_log(id)
);
