[package]
name = "rshanghai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Global variable
once_cell = "1.15.0"
# Command line parser
getopts = "0.2.21"
# Logging (abstract layer)
log = "0.4.17"
# Logging (concrete layer)
simplelog = "0.12.0"
# Daemon util
daemonize = "0.4.1"
# Time for log
time = "0.3.15"
# DateTime
chrono = "0.4.22"
# Json
serde_json = "1.0.86"
# Async
tokio = { version = "1", features = ["rt", "rt-multi-thread", "test-util"] }
# Http
reqwest = "0.11.12"
# URL encode
percent-encoding = "2.2.0"
# BASE64
base64 = "0.13.0"
# RNG
rand = "0.8.5"
# HMAC
hmac = "0.12.1"
sha1 = "0.10.5"

[dev-dependencies]
# Concurrent test control
serial_test = "0.9.0"
hex-literal = "0.3.4"
