[package]
name = "rshanghai"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Error handling
anyhow = "1.0.79"
thiserror = "1.0.56"
# Static assert
static_assertions = "1.1.0"
# Compiler version
rustc_version_runtime = "0.3.0"
# Bit flags
bitflags = "2.4.2"

# Command line parser
getopts = "0.2.21"
# Logging (abstract layer)
log = "0.4.20"
# Logging (concrete layer)
simplelog = "0.12.1"
# Daemon util
daemonize = "0.5.0"
# Time for log
time = "0.3.34"
chrono = { version = "0.4.33", features = ["clock", "iana-time-zone", "std"] }
# Json
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_with = { version = "3.6.1", features = ["json"] }
# TOML
toml = "0.8.10"

# Async
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "test-util", "macros", "signal", "fs", "process"] }
tokio-stream = "0.1.14"

# HTTP client
reqwest = { version = "0.11.24", features = ["json"] }
# URL encode
percent-encoding = "2.3.1"
# BASE64
base64 = "0.21.7"
# RNG
rand = "0.8.5"
# HMAC
hmac = "0.12.1"
sha1 = "0.10.6"
sha2 = "0.10.8"

# HTTP server
actix-web = "4.5.1"
actix-multipart = "0.6.1"
# Discord
serenity = "0.12.0"

# Image convert
image = "0.24.8"
# Font
rusttype="0.9.3"
# Scraping
scraper = "0.18.1"
# ChatGPT tokenizer
tiktoken-rs = "0.5.8"

[dev-dependencies]
# Concurrent test control
serial_test = "3.0.0"
hex-literal = "0.4.1"

[build-dependencies]
# Version info
vergen = { version = "8.3.1", features = ["git", "gitcl", "cargo"] }
