[package]
name = "rshanghai"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Error handling
anyhow = "1.0.75"
thiserror = "1.0.50"
# Static assert
static_assertions = "1.1.0"
# Compiler version
rustc_version_runtime = "0.3.0"
# Bit flags
bitflags = "2.4.1"

# Command line parser
getopts = "0.2.21"
# Logging (abstract layer)
log = "0.4.20"
# Logging (concrete layer)
simplelog = "0.12.1"
# Daemon util
daemonize = "0.5.0"
# Time for log
time = "0.3.30"
chrono = { version = "0.4.31", features = ["clock", "iana-time-zone", "std"] }
# Json
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_with = { version = "3.4.0", features = ["json"] }
# TOML
toml = "0.8.8"

# Async
tokio = { version = "1.34.0", features = ["rt", "rt-multi-thread", "test-util", "macros", "signal", "fs", "process"] }
tokio-stream = "0.1.14"
# HTTP
reqwest = "0.11.22"
# URL encode
percent-encoding = "2.3.1"
# BASE64
base64 = "0.21.5"
# RNG
rand = "0.8.5"
# HMAC
hmac = "0.12.1"
sha1 = "0.10.6"
sha2 = "0.10.8"
# HTTP Server
actix-web = "4.4.0"
actix-multipart = "0.6.1"
# Image convert
image = "0.24.7"
# Font
rusttype="0.9.3"
# Discord
serenity = "0.12.0"
scraper = "0.18.1"
tiktoken-rs = "0.5.7"

[dev-dependencies]
# Concurrent test control
serial_test = "2.0.0"
hex-literal = "0.4.1"

[build-dependencies]
# Version info
vergen = { version = "8.2.6", features = ["git", "gitcl", "cargo"] }
