[package]
name = "rshanghai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
log = "0.4.17"
simplelog = "0.12.0"
time = "0.3.15"
daemonize = "0.4.1"
