[package]
name = "rshanghai"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Error handling
anyhow = "1.0.66"
# Global variable
once_cell = "1.15.0"
# Static assert
static_assertions = "1.1.0"
# Compiler version
rustc_version_runtime = "0.2.1"
# Command line parser
getopts = "0.2.21"
# Logging (abstract layer)
log = "0.4.17"
# Logging (concrete layer)
simplelog = "0.12.0"
# Daemon util
daemonize = "0.5.0"
# Time for log
time = "0.3.15"
# DateTime
chrono = "0.4.23"
# Json
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.86"
# Async
tokio = { version = "1.23.1", features = ["rt", "rt-multi-thread", "test-util", "macros", "signal", "fs", "process"] }
# HTTP
reqwest = "0.11.12"
# URL encode
percent-encoding = "2.2.0"
# BASE64
base64 = "0.13.0"
# RNG
rand = "0.8.5"
# HMAC
hmac = "0.12.1"
sha1 = "0.10.5"
sha2 = "0.10.6"
# HTTP Server
actix-web = "4.2.1"
# Image convert
image = "0.24.5"
# Font
rusttype="0.9.3"
# Discord
serenity = "0.11.5"

[dev-dependencies]
# Concurrent test control
serial_test = "0.9.0"
hex-literal = "0.3.4"

[build-dependencies]
# Version info
vergen = "7.5.0"
