[package]
name = "rshanghai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.15.0"
getopts = "0.2.21"
log = "0.4.17"
simplelog = "0.12.0"
daemonize = "0.4.1"
time = "0.3.15"
chrono = "0.4.22"
serde_json = "1.0.86"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "test-util"] }

[dev-dependencies]
serial_test = "0.9.0"
