#!/bin/sh

# Automatic backup script
# Copy to:
# /etc/cron.weekly/

ROOT=/root/DollsKit/root
python3 ${ROOT}/bkup.py --mount-check --reserved-size 10 --exclude-from ${ROOT}/bkup_exclude.txt / /media/usbbkup
