[profile.dev]
panic = 'abort'
[profile.release]
panic = 'abort'

[package]
name = "mylog"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.40"
libc = "0.2.171"
log = { version = "0.4.27", features = ["std"] }
