# On push to main, checkout doc branch and works in it.

name: Build and Push Documents

on:
  push:
    branches:
      - main
env:
  PROJ_ROOT: ./shanghai
  DOC_OPTS: --no-deps --document-private-items
  REF: refs/heads/doc

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.REF }}
          fetch-depth: 0

      - name: Git Setup
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge from main
        run: |
          git merge --no-ff ${GITHUB_SHA}

      - name: Build
        working-directory: ${{ env.PROJ_ROOT }}
        run: |
          cargo doc ${DOC_OPTS} --workspace

      - name: Remove Old Data and Move
        run: |
          git rm --ignore-unmatch -r ./docs/doc
          mv ${{ env.PROJ_ROOT }}/target/doc ./docs/

      - name: Git Add
        run: |
          git add ./docs/doc

      - name: Git Commit
        continue-on-error: true
        run: |
          git commit -m "Update for ${GITHUB_REF} ${GITHUB_SHA}" -m "Automatic push by github actions"

      - name: Git Push
        run: |
          git push origin HEAD:${{ env.ref }}
