name: Auto Build and Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format
        working-directory: ./rshanghai
        run: cargo fmt -- --check
      - name: Clippy
        working-directory: ./rshanghai
        run: cargo clippy --no-deps -- -Dwarnings
      - name: Build
        working-directory: ./rshanghai
        run: cargo build --verbose
      - name: Test
        working-directory: ./rshanghai
        run: cargo test --verbose

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ./rshanghai
        run: cargo build --verbose --release
