name: Auto Build and Test

on: [push, pull_request]

# Make sure CI fails on all warnings, including Clippy lints
env:
  PROJ_ROOT: ./shanghai
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format
        working-directory: ${{ env.PROJ_ROOT }}
        run: cargo fmt -- --check
      - name: Clippy
        working-directory: ${{ env.PROJ_ROOT }}
        run: cargo clippy --all-targets --all-features
      - name: Build
        working-directory: ${{ env.PROJ_ROOT }}
        run: cargo build
      - name: Test
        working-directory: ${{ env.PROJ_ROOT }}
        run: cargo test

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        working-directory: ${{ env.PROJ_ROOT }}
        run: cargo build --release
