name: HTTPS Connection Test
on:
  schedule:
    # min[0,59] hour[0,23] day[1,31] mon[1,12] week[0,6; 0=Sunday]
    # 20:00 UTC = 05:00 JST
    - cron:  '37 20 * * *'
  workflow_dispatch:

permissions:
  contents: read

env:
  url: https://yappy-house.com/
  connect_timeout_seconds: 10
  max_time_seconds: 60

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: HTTPS Access
        run: |
          curl --fail \
            --connect-timeout "${{ env.connect_timeout_seconds }}" \
            --max-time "${{ env.max_time_seconds }}" \
            "${{ env.url }}"
